###############################################################################
# DO NOT EDIT THIS FILE! (Any changes will be overwritten.)
#
# Read the documentation here to see how to call each function and what kind of
# output to expect.
#
###############################################################################

import ctypes
import numpy
import os

from ctypes import (
    c_void_p,
    c_int,
    c_double,
)

# try to import the library
try:
    path_to_library = os.path.join('lib','libhomework3.so')
    homework3library = ctypes.cdll.LoadLibrary(path_to_library)
except OSError:
    raise OSError("You need to compile your homework library using 'make'.")

